site_name: Tonomy SDK
nav:
    - Home: index.md
    - Interact with identities (API): api.md
    - Manage SSO Applications (CLI): cli.md
    - Build smart wallets (SDK): sdk.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences