name: Run Tonomy-SDK Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run lint and test
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test:unit

  compile-contracts:
    name: Compiles contracts needed for bootstrap script
    runs-on: ubuntu-20.04
    container: eosio/eosio.cdt:v1.8.1
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Tonomy-Foundation/Tonomy-Contracts
          ref: development
          path: Tonomy-Contracts

      - name: Build eosio.bios.tonomy contract
        run: ./Tonomy-Contracts/contracts/eosio.bios.tonomy/build.sh local

      - name: Build eosio.token contract
        run: ./Tonomy-Contracts/contracts/eosio.token/build.sh local

      - name: Build id.tonomy contract
        run: ./Tonomy-Contracts/contracts/id.tonomy/build.sh local

      - name: Add Tonomy-Contracts dir to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tonomy-Contracts
          path: ./Tonomy-Contracts

  integration-test:
    needs: compile-contracts
    runs-on: ubuntu-20.04
    services:
      blockchain:
        image: tonomy/blockchain:initialized-development
        ports:
          - 8888:8888
      communication:
        image: tonomy/communication:development
        env:
          BLOCKCHAIN_URL: "http://blockchain:8888"
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      - name: Delete Tonomy-Contracts directory
        run: rm -rf ./Tonomy-Contracts

      - name: Get Tonomy-Contracts directory from artifacts
        uses: actions/download-artifact@v3
        with:
          name: Tonomy-Contracts
          path: ./Tonomy-Contracts

      - name: Install SDK and Bootstrap blockchain
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: npm run build:cli
      - run: npm run cli bootstrap

      - name: Run integration tests
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm run test:integration